### ISSUE TITLE
Quick feedback

### ISSUE THREAD

**Issue by jakesmolka** [thombergs/boxtime-cli#1]
Hey, I quickly checked out how boxtime compiles. I did run it for a moment afterwards and here are two points that caught my attention:

The task IDs are unhandy UUIDs. I would imagine they are quite uncomfortable from a user's perspective. Copy and paste works, but maybe auto-complete or simpler IDs (or even aliases) could make it easier to reference tasks.

The printed table on `task list` is slightly off in my case - see last line here:
``` bash
❯ ./build/native/nativeCompile/boxtime task list 
2022-12-25 11:56:28,030 INFO  Task ID                             | Task                        
2022-12-25 11:56:28,031 INFO  ------------------------------------|-----------------------------|
2022-12-25 11:56:28,031 INFO  593ba531-2759-4de3-8f66-f7abe9f70526| test 1                        |
``` 

Anyway, thanks for this project.

**Comment by thombergs** [comment]
Thanks! I have both things in my scopes!

Haven't put much effort in short IDs, yet, because I want to use it in an Alfred workflow eventually, where you choose a task from a list and Alfred passes the ID in the background so you don't need to worry about the ID at all.
